//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEFotoDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CEFotoDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CELogo {
            get {
                object obj = ResourceManager.GetObject("CELogo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] netherlands {
            get {
                object obj = ResourceManager.GetObject("netherlands", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        public static string StrAboutBtn {
            get {
                return ResourceManager.GetString("StrAboutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;E Webshop Foto Downloader.
        /// </summary>
        public static string StrAppTitle {
            get {
                return ResourceManager.GetString("StrAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Download.
        /// </summary>
        public static string StrDownloadBtn {
            get {
                return ResourceManager.GetString("StrDownloadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Opties.
        /// </summary>
        public static string StrDownloadOptions {
            get {
                return ResourceManager.GetString("StrDownloadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusief Extras.
        /// </summary>
        public static string StrExtra {
            get {
                return ResourceManager.GetString("StrExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoge kwaliteit.
        /// </summary>
        public static string StrHigh {
            get {
                return ResourceManager.GetString("StrHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lage kwaliteit.
        /// </summary>
        public static string StrLow {
            get {
                return ResourceManager.GetString("StrLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webshop foto downloader.
        /// </summary>
        public static string StrMainTitle {
            get {
                return ResourceManager.GetString("StrMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Downloads Folder.
        /// </summary>
        public static string StrOpenDownloadBtn {
            get {
                return ResourceManager.GetString("StrOpenDownloadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open een artikelen bestand....
        /// </summary>
        public static string StrOpenedFile {
            get {
                return ResourceManager.GetString("StrOpenedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open bestand.
        /// </summary>
        public static string StrOpenFileBtn {
            get {
                return ResourceManager.GetString("StrOpenFileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikelcode.
        /// </summary>
        public static string StrProductCode {
            get {
                return ResourceManager.GetString("StrProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StrStatus {
            get {
                return ResourceManager.GetString("StrStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een zip bestand.
        /// </summary>
        public static string StrZip {
            get {
                return ResourceManager.GetString("StrZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] united_kingdom {
            get {
                object obj = ResourceManager.GetObject("united_kingdom", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
